/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DashboardPanel.java
 *
 * Created on Feb 3, 2010, 4:34:05 PM
 */

package team192.dashboard.ui;

import edu.wpi.first.wpilibj.host.DashboardPacket;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JProgressBar;
import javax.swing.JSeparator;
import team192.spartango.ui.GraphComponent;
import javax.swing.JTextField;

/**
 *
 * @author anand
 */
public class DashboardPanel extends javax.swing.JPanel {

    public static final int SCALING_FACTOR = 100;
    private DashboardPacket dashboardData;
    private long startTime;

    /** Creates new form DashboardPanel */
    public DashboardPanel(DashboardPacket p) {
        initComponents();
        dashboardData = p;
        startTime = System.currentTimeMillis();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox();
        jComboBox2 = new javax.swing.JComboBox();
        jSeparator1 = new javax.swing.JSeparator();
        jProgressBar11 = new javax.swing.JProgressBar();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        graphComponent1 = new team192.spartango.ui.GraphComponent();
        graphComponent2 = new team192.spartango.ui.GraphComponent();
        graphComponent3 = new team192.spartango.ui.GraphComponent();
        graphComponent4 = new team192.spartango.ui.GraphComponent();
        graphComponent5 = new team192.spartango.ui.GraphComponent();
        graphComponent6 = new team192.spartango.ui.GraphComponent();
        graphComponent7 = new team192.spartango.ui.GraphComponent();
        graphComponent8 = new team192.spartango.ui.GraphComponent();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        graphComponent11 = new team192.spartango.ui.GraphComponent();
        graphComponent12 = new team192.spartango.ui.GraphComponent();
        graphComponent13 = new team192.spartango.ui.GraphComponent();
        graphComponent14 = new team192.spartango.ui.GraphComponent();
        graphComponent15 = new team192.spartango.ui.GraphComponent();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        graphComponent16 = new team192.spartango.ui.GraphComponent();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        graphComponent17 = new team192.spartango.ui.GraphComponent();
        graphComponent18 = new team192.spartango.ui.GraphComponent();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        graphComponent19 = new team192.spartango.ui.GraphComponent();
        graphComponent20 = new team192.spartango.ui.GraphComponent();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Digital Slot 1", "Digital Slot 2" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Analog Slot 1", "Analog Slot 2" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        jProgressBar11.setMaximum(140);
        jProgressBar11.setMinimum(90);

        jLabel19.setText("Battery");

        jLabel20.setText("Mode");

        graphComponent1.setMaximumSize(new java.awt.Dimension(294, 80));
        graphComponent1.setMinimumSize(new java.awt.Dimension(294, 80));

        javax.swing.GroupLayout graphComponent1Layout = new javax.swing.GroupLayout(graphComponent1);
        graphComponent1.setLayout(graphComponent1Layout);
        graphComponent1Layout.setHorizontalGroup(
            graphComponent1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 318, Short.MAX_VALUE)
        );
        graphComponent1Layout.setVerticalGroup(
            graphComponent1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        graphComponent2.setMaximumSize(new java.awt.Dimension(294, 80));
        graphComponent2.setMinimumSize(new java.awt.Dimension(294, 80));

        javax.swing.GroupLayout graphComponent2Layout = new javax.swing.GroupLayout(graphComponent2);
        graphComponent2.setLayout(graphComponent2Layout);
        graphComponent2Layout.setHorizontalGroup(
            graphComponent2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 306, Short.MAX_VALUE)
        );
        graphComponent2Layout.setVerticalGroup(
            graphComponent2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        graphComponent3.setMaximumSize(new java.awt.Dimension(294, 80));
        graphComponent3.setMinimumSize(new java.awt.Dimension(294, 80));

        javax.swing.GroupLayout graphComponent3Layout = new javax.swing.GroupLayout(graphComponent3);
        graphComponent3.setLayout(graphComponent3Layout);
        graphComponent3Layout.setHorizontalGroup(
            graphComponent3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 318, Short.MAX_VALUE)
        );
        graphComponent3Layout.setVerticalGroup(
            graphComponent3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        graphComponent4.setMaximumSize(new java.awt.Dimension(294, 80));
        graphComponent4.setMinimumSize(new java.awt.Dimension(294, 80));

        javax.swing.GroupLayout graphComponent4Layout = new javax.swing.GroupLayout(graphComponent4);
        graphComponent4.setLayout(graphComponent4Layout);
        graphComponent4Layout.setHorizontalGroup(
            graphComponent4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 306, Short.MAX_VALUE)
        );
        graphComponent4Layout.setVerticalGroup(
            graphComponent4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        graphComponent5.setMaximumSize(new java.awt.Dimension(294, 80));
        graphComponent5.setMinimumSize(new java.awt.Dimension(294, 80));

        javax.swing.GroupLayout graphComponent5Layout = new javax.swing.GroupLayout(graphComponent5);
        graphComponent5.setLayout(graphComponent5Layout);
        graphComponent5Layout.setHorizontalGroup(
            graphComponent5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 318, Short.MAX_VALUE)
        );
        graphComponent5Layout.setVerticalGroup(
            graphComponent5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        graphComponent6.setMaximumSize(new java.awt.Dimension(294, 80));
        graphComponent6.setMinimumSize(new java.awt.Dimension(294, 80));

        javax.swing.GroupLayout graphComponent6Layout = new javax.swing.GroupLayout(graphComponent6);
        graphComponent6.setLayout(graphComponent6Layout);
        graphComponent6Layout.setHorizontalGroup(
            graphComponent6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 306, Short.MAX_VALUE)
        );
        graphComponent6Layout.setVerticalGroup(
            graphComponent6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        graphComponent7.setMaximumSize(new java.awt.Dimension(294, 80));
        graphComponent7.setMinimumSize(new java.awt.Dimension(294, 80));

        javax.swing.GroupLayout graphComponent7Layout = new javax.swing.GroupLayout(graphComponent7);
        graphComponent7.setLayout(graphComponent7Layout);
        graphComponent7Layout.setHorizontalGroup(
            graphComponent7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 318, Short.MAX_VALUE)
        );
        graphComponent7Layout.setVerticalGroup(
            graphComponent7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        graphComponent8.setMaximumSize(new java.awt.Dimension(294, 80));
        graphComponent8.setMinimumSize(new java.awt.Dimension(294, 80));

        javax.swing.GroupLayout graphComponent8Layout = new javax.swing.GroupLayout(graphComponent8);
        graphComponent8.setLayout(graphComponent8Layout);
        graphComponent8Layout.setHorizontalGroup(
            graphComponent8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 306, Short.MAX_VALUE)
        );
        graphComponent8Layout.setVerticalGroup(
            graphComponent8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        jLabel11.setText("1");

        jLabel12.setText("2");

        jLabel13.setText("4");

        jLabel14.setText("3");

        jLabel15.setText("6");

        jLabel16.setText("5");

        jLabel17.setText("8");

        jLabel18.setText("7");

        jLabel21.setText("Status");

        jTextField1.setEditable(false);
        jTextField1.setText("Disconnected");

        jTextField2.setEditable(false);
        jTextField2.setText("Disconnected");

        jTextField3.setEditable(false);
        jTextField3.setText("Disconnected");

        graphComponent11.setMax(200.0);
        graphComponent11.setMaximumSize(new java.awt.Dimension(294, 80));
        graphComponent11.setMinimumSize(new java.awt.Dimension(294, 80));

        javax.swing.GroupLayout graphComponent11Layout = new javax.swing.GroupLayout(graphComponent11);
        graphComponent11.setLayout(graphComponent11Layout);
        graphComponent11Layout.setHorizontalGroup(
            graphComponent11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 184, Short.MAX_VALUE)
        );
        graphComponent11Layout.setVerticalGroup(
            graphComponent11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        graphComponent12.setMax(200.0);
        graphComponent12.setMaximumSize(new java.awt.Dimension(294, 80));
        graphComponent12.setMinimumSize(new java.awt.Dimension(294, 80));

        javax.swing.GroupLayout graphComponent12Layout = new javax.swing.GroupLayout(graphComponent12);
        graphComponent12.setLayout(graphComponent12Layout);
        graphComponent12Layout.setHorizontalGroup(
            graphComponent12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 184, Short.MAX_VALUE)
        );
        graphComponent12Layout.setVerticalGroup(
            graphComponent12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        graphComponent13.setMax(200.0);
        graphComponent13.setMaximumSize(new java.awt.Dimension(294, 80));
        graphComponent13.setMinimumSize(new java.awt.Dimension(294, 80));

        javax.swing.GroupLayout graphComponent13Layout = new javax.swing.GroupLayout(graphComponent13);
        graphComponent13.setLayout(graphComponent13Layout);
        graphComponent13Layout.setHorizontalGroup(
            graphComponent13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 184, Short.MAX_VALUE)
        );
        graphComponent13Layout.setVerticalGroup(
            graphComponent13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        graphComponent14.setMax(200.0);
        graphComponent14.setMaximumSize(new java.awt.Dimension(294, 80));
        graphComponent14.setMinimumSize(new java.awt.Dimension(294, 80));

        javax.swing.GroupLayout graphComponent14Layout = new javax.swing.GroupLayout(graphComponent14);
        graphComponent14.setLayout(graphComponent14Layout);
        graphComponent14Layout.setHorizontalGroup(
            graphComponent14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 184, Short.MAX_VALUE)
        );
        graphComponent14Layout.setVerticalGroup(
            graphComponent14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        graphComponent15.setMax(200.0);
        graphComponent15.setMaximumSize(new java.awt.Dimension(294, 80));
        graphComponent15.setMinimumSize(new java.awt.Dimension(294, 80));

        javax.swing.GroupLayout graphComponent15Layout = new javax.swing.GroupLayout(graphComponent15);
        graphComponent15.setLayout(graphComponent15Layout);
        graphComponent15Layout.setHorizontalGroup(
            graphComponent15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 184, Short.MAX_VALUE)
        );
        graphComponent15Layout.setVerticalGroup(
            graphComponent15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        jLabel1.setText("PWM 2");

        jLabel2.setText("PWM 1");

        jLabel3.setText("PWM 3");

        jLabel4.setText("PWM 4");

        jLabel5.setText("PWM 5");

        graphComponent16.setMax(200.0);
        graphComponent16.setMaximumSize(new java.awt.Dimension(294, 80));
        graphComponent16.setMinimumSize(new java.awt.Dimension(294, 80));

        javax.swing.GroupLayout graphComponent16Layout = new javax.swing.GroupLayout(graphComponent16);
        graphComponent16.setLayout(graphComponent16Layout);
        graphComponent16Layout.setHorizontalGroup(
            graphComponent16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 168, Short.MAX_VALUE)
        );
        graphComponent16Layout.setVerticalGroup(
            graphComponent16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        jLabel6.setText("PWM 9");

        jLabel7.setText("PWM 10");

        graphComponent17.setMax(200.0);
        graphComponent17.setMaximumSize(new java.awt.Dimension(294, 80));
        graphComponent17.setMinimumSize(new java.awt.Dimension(294, 80));

        javax.swing.GroupLayout graphComponent17Layout = new javax.swing.GroupLayout(graphComponent17);
        graphComponent17.setLayout(graphComponent17Layout);
        graphComponent17Layout.setHorizontalGroup(
            graphComponent17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 168, Short.MAX_VALUE)
        );
        graphComponent17Layout.setVerticalGroup(
            graphComponent17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        graphComponent18.setMax(200.0);
        graphComponent18.setMaximumSize(new java.awt.Dimension(294, 80));
        graphComponent18.setMinimumSize(new java.awt.Dimension(294, 80));

        javax.swing.GroupLayout graphComponent18Layout = new javax.swing.GroupLayout(graphComponent18);
        graphComponent18.setLayout(graphComponent18Layout);
        graphComponent18Layout.setHorizontalGroup(
            graphComponent18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 168, Short.MAX_VALUE)
        );
        graphComponent18Layout.setVerticalGroup(
            graphComponent18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        jLabel8.setText("PWM 7");

        jLabel9.setText("PWM 6");

        jLabel10.setText("PWM 8");

        graphComponent19.setMax(200.0);
        graphComponent19.setMaximumSize(new java.awt.Dimension(294, 80));
        graphComponent19.setMinimumSize(new java.awt.Dimension(294, 80));

        javax.swing.GroupLayout graphComponent19Layout = new javax.swing.GroupLayout(graphComponent19);
        graphComponent19.setLayout(graphComponent19Layout);
        graphComponent19Layout.setHorizontalGroup(
            graphComponent19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 168, Short.MAX_VALUE)
        );
        graphComponent19Layout.setVerticalGroup(
            graphComponent19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        graphComponent20.setMax(200.0);
        graphComponent20.setMaximumSize(new java.awt.Dimension(294, 80));
        graphComponent20.setMinimumSize(new java.awt.Dimension(294, 80));

        javax.swing.GroupLayout graphComponent20Layout = new javax.swing.GroupLayout(graphComponent20);
        graphComponent20.setLayout(graphComponent20Layout);
        graphComponent20Layout.setHorizontalGroup(
            graphComponent20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 168, Short.MAX_VALUE)
        );
        graphComponent20Layout.setVerticalGroup(
            graphComponent20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel14)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel11))
                                        .addComponent(graphComponent7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(graphComponent5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(graphComponent1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(graphComponent3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(jLabel18))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(graphComponent8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(graphComponent6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(graphComponent2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel17)
                                            .addComponent(jLabel12)
                                            .addComponent(graphComponent4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(247, 247, 247)
                                        .addComponent(jLabel13))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(247, 247, 247)
                                        .addComponent(jLabel15))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addGap(28, 28, 28)
                                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jProgressBar11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel21)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel20)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel9))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(graphComponent11, javax.swing.GroupLayout.Alignment.LEADING, 0, 184, Short.MAX_VALUE)
                            .addComponent(graphComponent13, javax.swing.GroupLayout.Alignment.LEADING, 0, 184, Short.MAX_VALUE)
                            .addComponent(graphComponent12, javax.swing.GroupLayout.Alignment.LEADING, 0, 184, Short.MAX_VALUE)
                            .addComponent(graphComponent14, javax.swing.GroupLayout.Alignment.LEADING, 0, 184, Short.MAX_VALUE)
                            .addComponent(graphComponent15, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 184, Short.MAX_VALUE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(graphComponent19, 0, 168, Short.MAX_VALUE)
                            .addComponent(graphComponent17, javax.swing.GroupLayout.Alignment.LEADING, 0, 168, Short.MAX_VALUE)
                            .addComponent(graphComponent18, 0, 168, Short.MAX_VALUE)
                            .addComponent(graphComponent16, javax.swing.GroupLayout.PREFERRED_SIZE, 168, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(graphComponent20, 0, 168, Short.MAX_VALUE))
                            .addComponent(jLabel7)
                            .addComponent(jLabel6)
                            .addComponent(jLabel8)
                            .addComponent(jLabel10))))
                .addContainerGap(76, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(10, 10, 10))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addComponent(graphComponent1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel14)
                                .addGap(4, 4, 4)
                                .addComponent(graphComponent3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel12)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel9)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(graphComponent2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel13)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(graphComponent4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(graphComponent15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(jLabel1)
                                                    .addComponent(jLabel8)))
                                            .addComponent(graphComponent16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(graphComponent18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(graphComponent14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel16))
                                .addGap(4, 4, 4)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(graphComponent5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel18)
                                        .addGap(4, 4, 4)
                                        .addComponent(graphComponent7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(graphComponent6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(4, 4, 4)
                                        .addComponent(jLabel17)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(graphComponent8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(30, 30, 30)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel19)
                                    .addComponent(jLabel21)
                                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel20)
                                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jProgressBar11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(graphComponent12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(graphComponent19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel6))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(graphComponent13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(4, 4, 4)
                                        .addComponent(jLabel5))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(114, 114, 114)
                                        .addComponent(jLabel7)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(graphComponent20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(graphComponent11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(229, 229, 229)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(106, 106, 106)
                        .addComponent(graphComponent17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(305, 305, 305)))
                .addContainerGap(105, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    public void update(){
        double time = (System.currentTimeMillis() - startTime)/10;
        if(jComboBox1.getSelectedItem().equals("Digital Slot 1")){
            graphComponent11.addPoint(time,SCALING_FACTOR+SCALING_FACTOR*dashboardData.cRioState.digitalModule1.pwmValues[0]);
            graphComponent12.addPoint(time,SCALING_FACTOR+SCALING_FACTOR*dashboardData.cRioState.digitalModule1.pwmValues[1]);
            graphComponent13.addPoint(time,SCALING_FACTOR+SCALING_FACTOR*dashboardData.cRioState.digitalModule1.pwmValues[2]);
            graphComponent14.addPoint(time,SCALING_FACTOR+SCALING_FACTOR*dashboardData.cRioState.digitalModule1.pwmValues[3]);
            graphComponent15.addPoint(time,SCALING_FACTOR+SCALING_FACTOR*dashboardData.cRioState.digitalModule1.pwmValues[4]);
            graphComponent16.addPoint(time,SCALING_FACTOR+SCALING_FACTOR*dashboardData.cRioState.digitalModule1.pwmValues[5]);
            graphComponent17.addPoint(time,SCALING_FACTOR+SCALING_FACTOR*dashboardData.cRioState.digitalModule1.pwmValues[6]);
            graphComponent18.addPoint(time,SCALING_FACTOR+SCALING_FACTOR*dashboardData.cRioState.digitalModule1.pwmValues[7]);
            graphComponent19.addPoint(time,SCALING_FACTOR+SCALING_FACTOR*dashboardData.cRioState.digitalModule1.pwmValues[8]);
            graphComponent20.addPoint(time,SCALING_FACTOR+SCALING_FACTOR*dashboardData.cRioState.digitalModule1.pwmValues[9]);
        } else {
            graphComponent11.addPoint(time,SCALING_FACTOR+SCALING_FACTOR*dashboardData.cRioState.digitalModule2.pwmValues[0]);
            graphComponent12.addPoint(time,SCALING_FACTOR+SCALING_FACTOR*dashboardData.cRioState.digitalModule2.pwmValues[1]);
            graphComponent13.addPoint(time,SCALING_FACTOR+SCALING_FACTOR*dashboardData.cRioState.digitalModule2.pwmValues[2]);
            graphComponent14.addPoint(time,SCALING_FACTOR+SCALING_FACTOR*dashboardData.cRioState.digitalModule2.pwmValues[3]);
            graphComponent15.addPoint(time,SCALING_FACTOR+SCALING_FACTOR*dashboardData.cRioState.digitalModule2.pwmValues[4]);
            graphComponent16.addPoint(time,SCALING_FACTOR+SCALING_FACTOR*dashboardData.cRioState.digitalModule2.pwmValues[5]);
            graphComponent17.addPoint(time,SCALING_FACTOR+SCALING_FACTOR*dashboardData.cRioState.digitalModule2.pwmValues[6]);
            graphComponent18.addPoint(time,SCALING_FACTOR+SCALING_FACTOR*dashboardData.cRioState.digitalModule2.pwmValues[7]);
            graphComponent19.addPoint(time,SCALING_FACTOR+SCALING_FACTOR*dashboardData.cRioState.digitalModule2.pwmValues[8]);
            graphComponent20.addPoint(time,SCALING_FACTOR+SCALING_FACTOR*dashboardData.cRioState.digitalModule2.pwmValues[9]);
        }

        if(jComboBox2.getSelectedItem().equals("Analog Slot 1")){
            graphComponent1.addPoint(time, dashboardData.cRioState.analogModule1.input0);
            graphComponent2.addPoint(time, dashboardData.cRioState.analogModule1.input1);
            graphComponent3.addPoint(time, dashboardData.cRioState.analogModule1.input2);
            graphComponent4.addPoint(time, dashboardData.cRioState.analogModule1.input3);
            graphComponent5.addPoint(time, dashboardData.cRioState.analogModule1.input4);
            graphComponent6.addPoint(time, dashboardData.cRioState.analogModule1.input5);
            graphComponent7.addPoint(time, dashboardData.cRioState.analogModule1.input6);
            graphComponent8.addPoint(time, dashboardData.cRioState.analogModule1.input7);
        } else {
            graphComponent1.addPoint(time, dashboardData.cRioState.analogModule2.input0);
            graphComponent2.addPoint(time, dashboardData.cRioState.analogModule2.input1);
            graphComponent3.addPoint(time, dashboardData.cRioState.analogModule2.input2);
            graphComponent4.addPoint(time, dashboardData.cRioState.analogModule2.input3);
            graphComponent5.addPoint(time, dashboardData.cRioState.analogModule2.input4);
            graphComponent6.addPoint(time, dashboardData.cRioState.analogModule2.input5);
            graphComponent7.addPoint(time, dashboardData.cRioState.analogModule2.input6);
            graphComponent8.addPoint(time, dashboardData.cRioState.analogModule2.input7);
        }

        jProgressBar11.setValue((int) Math.round(10*(dashboardData.driverStationState.getBatteryVoltageWhole()/1.5+dashboardData.driverStationState.getBatteryVoltageDecimal()/135.0)));
        jTextField3.setText(dashboardData.driverStationState.getBatteryVoltageWhole()+" | "+dashboardData.driverStationState.getBatteryVoltageDecimal());
        jTextField1.setText((dashboardData.driverStationState.isIsEnabled()? "Enabled" : "Disabled"));
        jTextField2.setText((dashboardData.driverStationState.isIsAutonomous()? "Autonomous" : "Teleoperated"));
        this.repaint();
    }

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private team192.spartango.ui.GraphComponent graphComponent1;
    private team192.spartango.ui.GraphComponent graphComponent11;
    private team192.spartango.ui.GraphComponent graphComponent12;
    private team192.spartango.ui.GraphComponent graphComponent13;
    private team192.spartango.ui.GraphComponent graphComponent14;
    private team192.spartango.ui.GraphComponent graphComponent15;
    private team192.spartango.ui.GraphComponent graphComponent16;
    private team192.spartango.ui.GraphComponent graphComponent17;
    private team192.spartango.ui.GraphComponent graphComponent18;
    private team192.spartango.ui.GraphComponent graphComponent19;
    private team192.spartango.ui.GraphComponent graphComponent2;
    private team192.spartango.ui.GraphComponent graphComponent20;
    private team192.spartango.ui.GraphComponent graphComponent3;
    private team192.spartango.ui.GraphComponent graphComponent4;
    private team192.spartango.ui.GraphComponent graphComponent5;
    private team192.spartango.ui.GraphComponent graphComponent6;
    private team192.spartango.ui.GraphComponent graphComponent7;
    private team192.spartango.ui.GraphComponent graphComponent8;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JProgressBar jProgressBar11;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables

    public GraphComponent getGraphComponent1() {
        return graphComponent1;
    }

    public GraphComponent getGraphComponent2() {
        return graphComponent2;
    }

    public GraphComponent getGraphComponent3() {
        return graphComponent3;
    }

    public GraphComponent getGraphComponent4() {
        return graphComponent4;
    }

    public GraphComponent getGraphComponent5() {
        return graphComponent5;
    }

    public GraphComponent getGraphComponent6() {
        return graphComponent6;
    }

    public GraphComponent getGraphComponent7() {
        return graphComponent7;
    }

    public GraphComponent getGraphComponent8() {
        return graphComponent8;
    }
    public JComboBox getjComboBox1() {
        return jComboBox1;
    }

    public JComboBox getjComboBox2() {
        return jComboBox2;
    }

    public JLabel getjLabel1() {
        return jLabel1;
    }

    public JLabel getjLabel10() {
        return jLabel10;
    }

    public JLabel getjLabel11() {
        return jLabel11;
    }

    public JLabel getjLabel12() {
        return jLabel12;
    }

    public JLabel getjLabel13() {
        return jLabel13;
    }

    public JLabel getjLabel14() {
        return jLabel14;
    }

    public JLabel getjLabel15() {
        return jLabel15;
    }

    public JLabel getjLabel16() {
        return jLabel16;
    }

    public JLabel getjLabel17() {
        return jLabel17;
    }

    public JLabel getjLabel18() {
        return jLabel18;
    }

    public JLabel getjLabel19() {
        return jLabel19;
    }

    public JLabel getjLabel2() {
        return jLabel2;
    }

    public JLabel getjLabel20() {
        return jLabel20;
    }

    public JLabel getjLabel3() {
        return jLabel3;
    }

    public JLabel getjLabel4() {
        return jLabel4;
    }

    public JLabel getjLabel5() {
        return jLabel5;
    }

    public JLabel getjLabel6() {
        return jLabel6;
    }

    public JLabel getjLabel7() {
        return jLabel7;
    }

    public JLabel getjLabel8() {
        return jLabel8;
    }

    public JLabel getjLabel9() {
        return jLabel9;
    }

    public JSeparator getjSeparator1() {
        return jSeparator1;
    }

    public DashboardPacket getDashboardData() {
        return dashboardData;
    }

    public GraphComponent getGraphComponent11() {
        return graphComponent11;
    }

    public GraphComponent getGraphComponent12() {
        return graphComponent12;
    }

    public GraphComponent getGraphComponent13() {
        return graphComponent13;
    }

    public GraphComponent getGraphComponent14() {
        return graphComponent14;
    }

    public GraphComponent getGraphComponent15() {
        return graphComponent15;
    }

    public GraphComponent getGraphComponent16() {
        return graphComponent16;
    }

    public GraphComponent getGraphComponent17() {
        return graphComponent17;
    }

    public GraphComponent getGraphComponent18() {
        return graphComponent18;
    }

    public GraphComponent getGraphComponent19() {
        return graphComponent19;
    }

    public GraphComponent getGraphComponent20() {
        return graphComponent20;
    }

    public JLabel getjLabel21() {
        return jLabel21;
    }

    public JProgressBar getjProgressBar11() {
        return jProgressBar11;
    }

    public JTextField getjTextField1() {
        return jTextField1;
    }

    public JTextField getjTextField2() {
        return jTextField2;
    }

    public JTextField getjTextField3() {
        return jTextField3;
    }

    public long getStartTime() {
        return startTime;
    }


    
}
